name: guess-the-prompt
region: nyc
services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/compare-images
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: FAL_AI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: MODEL_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: GENERAL


